import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Autor from '/components/CadaAutor.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.query.id
  const response = await axios.get("https://skeleton-nodejs.guilhermetombin.repl.co/autor/" + id)
  const autor = response.data
  const data = autor[0]
 return{
   props: {
     data
   }
 }
}

export default function Autor_unico({data}){
  return(
    <div className={styles.container}>
       <Head>
        <title>Autor: {data.nome}</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
        <Autor id={data.id} nome={data.nome} sobrenome={data.sobrenome} data_de_nascimento={data.data_de_nascimento}/>
      </main>
      <footer className={styles.footer}>
          Guilherme Ferreira Tombini - INFO 5A
      </footer>
      
    </div>
  ) 
}