import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Autor from '/components/CadaAutor.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.params.id
  const response = await axios.get(`https://projetofinal-ptas2.guilhermetombin.repl.co/autors/${id}`)
  const autor = response.data
 return{
   props: {
     autor
   }
 }
}

export default function Autor_unico({autor}){
  return(
    <div className={styles.container}>
       <Head>
        <title>Autor: {autor.nome}</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
        <Autor id={autor.id} nome={autor.nome} sobrenome={autor.sobrenome} data_nascimento={autor.data_nascimento}/>
      </main>
      <footer className={styles.footer}>
          Guilherme Tombini, Rafael Albuquerque - INFO 5A
      </footer>
      
    </div>
  ) 
}