import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Livros_autor from '/components/Livros_autor.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.params.id
  const response = await axios.get(`https://projetofinal-ptas2.guilhermetombin.repl.co/livros/${id}/autors`)
  const autor = response.data
 return{
   props: {
     autor
   }
 }
}


export default function Livro_autores({autor}){
  return(
    <div className={styles.container}>
       <Head>
        <title>Autores do livro</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
       <Livros_autor id={autor.id} nome={autor.nome} sobrenome={autor.sobrenome} data_nascimento={autor.data_nascimento}/>
      </main>
      <footer className={styles.footer}>
          Guilherme Tombini, Rafael Albuquerque - INFO 5A
      </footer>
      
    </div>
  ) 
}