import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Autor_livro from '/components/Autor_livros.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.params.id
  const response = await axios.get(`https://projetofinal-ptas2.guilhermetombin.repl.co/autors/${id}/livros`)
  const autor = response.data
 return{
   props: {
     autor
   }
 }
}

export default function Autor_Livro({autor}){
  return(
    <div className={styles.container}>
       <Head>
        <title>livros do autor</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
        {autor.map(autor => {return(
          <Autor_livro id={autor.id} titulo={autor.titulo} editora={autor.editora} preco={autor.preco}/>
        )})}
      </main>
      <footer className={styles.footer}>
          Guilherme Tombini, Rafael Albuquerque - INFO 5A
      </footer>
      
    </div>
  ) 
}