import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Card1 from '/components/Alterar_autores.js'

export default function Autores(){
  return(
    <div className={styles.container}>
    <Head>
        <title>Alterar Autor</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
    <Menu/>
    <main className={styles.main}>
     <Card1/>
    </main>
    <footer className={styles.footer}>
          Guilherme Ferreira Tombini - INFO 5A
      </footer>
    </div>
  ) 
}