import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Form from '/components/Card2.js'

export default function Cadastro_livros(){
  return(
    <div className={styles.container}>
    <Head>
        <title>Cadastro de livros</title>Will
        <meta name="description" content="Generated by create next app" /> 
      </Head>
    <Menu/>
    <main className={styles.main}>
     <Form/>
    </main>
    <footer className={styles.footer}>
          Guilherme Tombini, Rafael Albuquerque - INFO 5A
      </footer>
    </div>
  ) 
}