import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Livro from '/components/Cadalivro.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.query.id
  const response = await axios.get("https://skeleton-nodejs.guilhermetombin.repl.co/livro/" + id)
  const livro = response.data
  const data = livro[0]
 return{
   props: {
     data
   }
 }
}

export default function Livro_unico({data}){
  return(
    <div className={styles.container}>
       <Head>
        <title>{data.titulo}</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
        <Livro id={data.id} titulo={data.titulo} editora={data.editora} data_publicacao={data.data_publicacao} preco={data.preco} autor={data.autor_id}/>
      </main>
      <footer className={styles.footer}>
          Guilherme Ferreira Tombini - INFO 5A
      </footer>
      
    </div>
  ) 
}