import Link from 'next/link'
import Image from 'next/image'
import styles from '/styles/Home.module.css'
import Head from 'next/head'
import Menu from '/components/Menu.js'
import Atualiza from '/components/Alterar_livros.js'
import axios from 'axios'

export async function getServerSideProps(context) {
  const id = context.params.id
  const response = await axios.get("https://projetofinal-ptas2.guilhermetombin.repl.co/livros/" + id)
  const livro = response.data
 return{
   props: {
     livro
   }
 }
}

export default function Livros({livro}){
  return(
    <div className={styles.container}>
       <Head>
        <title>Alterar de Livro</title>
        <meta name="description" content="Generated by create next app" /> 
      </Head>
      <Menu/>
      <main className={styles.main}>
      <Atualiza id={livro.id} titulo={livro.titulo} editora={livro.editora} data_publicacao={livro.data_publicacao} preco={livro.preco} autor={livro.autorId}/>
      </main>
      <footer className={styles.footer}>
         Guilherme Tombini, Rafael Albuquerque - INFO 5A
      </footer>
      
    </div>
  ) 
}